### ISSUE TITLE
Build failing on Launchpad during git clone operation.

### ISSUE THREAD

**Issue by locnnil** [canonical/matter-pi-gpio-commander#62]
Launchpad build log:

```log
[09/Apr/2024:06:15:02 +0000] "CONNECT github.com:443 HTTP/1.1" 200 49427057 "-" "git/2.34.1"
:: + scripts/checkout_submodules.py --shallow --platform linux
:: Checking out: nlassert, nlio, nlunit-test, mbedtls, qrcode, pigweed, openthread, ot-br-posix, cirque, nanopb, ot-stm32, third_party/pybind11/repo, third_party/jsoncpp/repo, editline, third_party/boringssl/repo/src, third_party/libwebsockets/repo, third_party/imgui/repo, perfetto
[09/Apr/2024:06:15:05 +0000] "CONNECT github.com:443 HTTP/1.1" 200 181618 "-" "git/2.34.1"
[09/Apr/2024:06:15:08 +0000] "CONNECT github.com:443 HTTP/1.1" 200 35441910 "-" "git/2.34.1"
[09/Apr/2024:06:15:09 +0000] "CONNECT github.com:443 HTTP/1.1" 200 74164 "-" "git/2.34.1"
[09/Apr/2024:06:15:12 +0000] "CONNECT github.com:443 HTTP/1.1" 200 63656 "-" "git/2.34.1"
[09/Apr/2024:06:15:14 +0000] "CONNECT github.com:443 HTTP/1.1" 200 1728361 "-" "git/2.34.1"
[09/Apr/2024:06:15:15 +0000] "CONNECT github.com:443 HTTP/1.1" 200 208151 "-" "git/2.34.1"
[09/Apr/2024:06:15:18 +0000] "CONNECT github.com:443 HTTP/1.1" 200 16884377 "-" "git/2.34.1"
[09/Apr/2024:06:15:19 +0000] "CONNECT github.com:443 HTTP/1.1" 200 5539059 "-" "git/2.34.1"
[09/Apr/2024:06:15:21 +0000] "CONNECT github.com:443 HTTP/1.1" 200 1266169 "-" "git/2.34.1"
[09/Apr/2024:06:15:23 +0000] "CONNECT github.com:443 HTTP/1.1" 200 582676 "-" "git/2.34.1"
[09/Apr/2024:06:15:24 +0000] "CONNECT github.com:443 HTTP/1.1" 200 578146 "-" "git/2.34.1"
[09/Apr/2024:06:15:25 +0000] "CONNECT github.com:443 HTTP/1.1" 200 530441 "-" "git/2.34.1"
[09/Apr/2024:06:15:27 +0000] "CONNECT github.com:443 HTTP/1.1" 200 8894100 "-" "git/2.34.1"
[09/Apr/2024:06:15:29 +0000] "CONNECT github.com:443 HTTP/1.1" 200 8893760 "-" "git/2.34.1"
[09/Apr/2024:06:15:31 +0000] "CONNECT github.com:443 HTTP/1.1" 200 1069302 "-" "git/2.34.1"
[09/Apr/2024:06:15:33 +0000] "CONNECT github.com:443 HTTP/1.1" 200 22986078 "-" "git/2.34.1"
[09/Apr/2024:06:15:36 +0000] "CONNECT github.com:443 HTTP/1.1" 200 9150416 "-" "git/2.34.1"
[09/Apr/2024:06:15:37 +0000] "CONNECT github.com:443 HTTP/1.1" 200 871582 "-" "git/2.34.1"
[09/Apr/2024:06:15:38 +0000] "CONNECT github.com:443 HTTP/1.1" 200 6755 "-" "git/2.34.1"
[09/Apr/2024:06:15:40 +0000] "CONNECT github.com:443 HTTP/1.1" 200 59004 "-" "git/2.34.1"
[09/Apr/2024:06:15:41 +0000] "CONNECT github.com:443 HTTP/1.1" 200 7511 "-" "git/2.34.1"
[09/Apr/2024:06:15:43 +0000] "CONNECT github.com:443 HTTP/1.1" 200 2581807 "-" "git/2.34.1"
[09/Apr/2024:06:15:45 +0000] "CONNECT github.com:443 HTTP/1.1" 200 12382 "-" "git/2.34.1"
[09/Apr/2024:06:15:46 +0000] "CONNECT github.com:443 HTTP/1.1" 200 120420 "-" "git/2.34.1"
[09/Apr/2024:06:15:48 +0000] "CONNECT github.com:443 HTTP/1.1" 200 12650 "-" "git/2.34.1"
[09/Apr/2024:06:15:49 +0000] "CONNECT github.com:443 HTTP/1.1" 200 83133 "-" "git/2.34.1"
[09/Apr/2024:06:15:50 +0000] "CONNECT github.com:443 HTTP/1.1" 200 34982 "-" "git/2.34.1"
[09/Apr/2024:06:15:52 +0000] "CONNECT github.com:443 HTTP/1.1" 200 1616206 "-" "git/2.34.1"
[09/Apr/2024:06:15:54 +0000] "CONNECT github.com:443 HTTP/1.1" 200 6442 "-" "git/2.34.1"
[09/Apr/2024:06:15:57 +0000] "CONNECT github.com:443 HTTP/1.1" 200 2480747 "-" "git/2.34.1"
[09/Apr/2024:06:15:59 +0000] "CONNECT github.com:443 HTTP/1.1" 200 6444 "-" "git/2.34.1"
[09/Apr/2024:06:16:01 +0000] "CONNECT github.com:443 HTTP/1.1" 200 675437 "-" "git/2.34.1"
[09/Apr/2024:06:16:03 +0000] "CONNECT github.com:443 HTTP/1.1" 200 5905 "-" "git/2.34.1"
[09/Apr/2024:06:16:04 +0000] "CONNECT github.com:443 HTTP/1.1" 200 135952 "-" "git/2.34.1"
[09/Apr/2024:06:16:05 +0000] "CONNECT github.com:443 HTTP/1.1" 200 11820 "-" "git/2.34.1"
[09/Apr/2024:06:16:07 +0000] "CONNECT github.com:443 HTTP/1.1" 200 3267874 "-" "git/2.34.1"
[09/Apr/2024:06:16:09 +0000] "CONNECT github.com:443 HTTP/1.1" 200 5389 "-" "git/2.34.1"
[09/Apr/2024:06:16:12 +0000] "CONNECT github.com:443 HTTP/1.1" 200 404135 "-" "git/2.34.1"
[09/Apr/2024:06:16:14 +0000] "CONNECT github.com:443 HTTP/1.1" 200 11647 "-" "git/2.34.1"
[09/Apr/2024:06:16:15 +0000] "CONNECT github.com:443 HTTP/1.1" 200 203273 "-" "git/2.34.1"
Pulling libgpiod
[09/Apr/2024:06:16:16 +0000] "CONNECT git.kernel.org:9418 HTTP/1.0" 200 56686 "-" "-"
Failed to pull source: command ['git', 'clone', '--recursive', '--branch', 'v2.1', 'git://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git', '/build/matter-pi-gpio-commander/parts/libgpiod/src'] exited with code 128.
Make sure sources are correctly specified.
Full execution log: '/root/.local/state/snapcraft/log/snapcraft-20240409-061345.223713.log'
Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 265, in run
    self.pull()
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 205, in pull
    self.run_build_command(
  File "/usr/lib/python3/dist-packages/lpbuildd/target/operation.py", line 62, in run_build_command
    return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/lxd.py", line 718, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lxc', 'exec', 'lp-jammy-arm64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/lpbuildd-git-proxy', '--env', 'SNAPPY_STORE_NO_CDN=1', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build-request-id": "lp-87860346", "build-request-timestamp": "2024-04-09T06:10:51Z", "build_url": "https://launchpad.net/~build.snapcraft.io/+snap/23e77e65b0e55be1a2f0abd873ad22d8/+build/2445776"}', '--env', 'SNAPCRAFT_BUILD_ENVIRONMENT=host', '--', '/bin/sh', '-c', 'cd /build/matter-pi-gpio-commander && linux64 snapcraft pull']' returned non-zero exit status 1.
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=jammy --arch=arm64 SNAPBUILD-2445776
Scanning for processes to kill in build SNAPBUILD-2445776
```

**Comment by farshidtz** [comment]
The build have started to fail since https://github.com/canonical/matter-pi-gpio-commander/pull/56
